/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package LaboNotification-0.1.0.0 */
#ifndef VERSION_LaboNotification
#define VERSION_LaboNotification "0.1.0.0"
#endif /* VERSION_LaboNotification */
#ifndef MIN_VERSION_LaboNotification
#define MIN_VERSION_LaboNotification(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_LaboNotification */
/* package HaskellNet-0.6.0.2 */
#ifndef VERSION_HaskellNet
#define VERSION_HaskellNet "0.6.0.2"
#endif /* VERSION_HaskellNet */
#ifndef MIN_VERSION_HaskellNet
#define MIN_VERSION_HaskellNet(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_HaskellNet */
/* package HaskellNet-SSL-0.3.4.4 */
#ifndef VERSION_HaskellNet_SSL
#define VERSION_HaskellNet_SSL "0.3.4.4"
#endif /* VERSION_HaskellNet_SSL */
#ifndef MIN_VERSION_HaskellNet_SSL
#define MIN_VERSION_HaskellNet_SSL(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_HaskellNet_SSL */
/* package LaboNotification-0.1.0.0 */
#ifndef VERSION_LaboNotification
#define VERSION_LaboNotification "0.1.0.0"
#endif /* VERSION_LaboNotification */
#ifndef MIN_VERSION_LaboNotification
#define MIN_VERSION_LaboNotification(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_LaboNotification */
/* package aeson-2.0.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.0.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package bytestring-0.11.3.1 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.3.1"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 3)
#endif /* MIN_VERSION_bytestring */
/* package daemons-0.3.0 */
#ifndef VERSION_daemons
#define VERSION_daemons "0.3.0"
#endif /* VERSION_daemons */
#ifndef MIN_VERSION_daemons
#define MIN_VERSION_daemons(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_daemons */
/* package direct-daemonize-3.1 */
#ifndef VERSION_direct_daemonize
#define VERSION_direct_daemonize "3.1"
#endif /* VERSION_direct_daemonize */
#ifndef MIN_VERSION_direct_daemonize
#define MIN_VERSION_direct_daemonize(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_direct_daemonize */
/* package fast-logger-3.1.1 */
#ifndef VERSION_fast_logger
#define VERSION_fast_logger "3.1.1"
#endif /* VERSION_fast_logger */
#ifndef MIN_VERSION_fast_logger
#define MIN_VERSION_fast_logger(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_fast_logger */
/* package odd-jobs-0.2.2 */
#ifndef VERSION_odd_jobs
#define VERSION_odd_jobs "0.2.2"
#endif /* VERSION_odd_jobs */
#ifndef MIN_VERSION_odd_jobs
#define MIN_VERSION_odd_jobs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_odd_jobs */
/* package postgresql-simple-0.6.4 */
#ifndef VERSION_postgresql_simple
#define VERSION_postgresql_simple "0.6.4"
#endif /* VERSION_postgresql_simple */
#ifndef MIN_VERSION_postgresql_simple
#define MIN_VERSION_postgresql_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 4)
#endif /* MIN_VERSION_postgresql_simple */
/* package resource-pool-0.2.3.2 */
#ifndef VERSION_resource_pool
#define VERSION_resource_pool "0.2.3.2"
#endif /* VERSION_resource_pool */
#ifndef MIN_VERSION_resource_pool
#define MIN_VERSION_resource_pool(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_resource_pool */
/* package servant-server-0.19.2 */
#ifndef VERSION_servant_server
#define VERSION_servant_server "0.19.2"
#endif /* VERSION_servant_server */
#ifndef MIN_VERSION_servant_server
#define MIN_VERSION_servant_server(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  19 || \
  (major1) == 0 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_servant_server */
/* package text-1.2.5.0 */
#ifndef VERSION_text
#define VERSION_text "1.2.5.0"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_VERSION_text */
/* package time-1.11.1.1 */
#ifndef VERSION_time
#define VERSION_time "1.11.1.1"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  11 || \
  (major1) == 1 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_time */
/* package timing-convenience-0.1 */
#ifndef VERSION_timing_convenience
#define VERSION_timing_convenience "0.1"
#endif /* VERSION_timing_convenience */
#ifndef MIN_VERSION_timing_convenience
#define MIN_VERSION_timing_convenience(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_timing_convenience */
/* package wai-3.2.3 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.3"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_wai */
/* package warp-3.3.23 */
#ifndef VERSION_warp
#define VERSION_warp "3.3.23"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  3 || \
  (major1) == 3 && (major2) == 3 && (minor) <= 23)
#endif /* MIN_VERSION_warp */

/* tool alex-3.2.5 */
#ifndef TOOL_VERSION_alex
#define TOOL_VERSION_alex "3.2.5"
#endif /* TOOL_VERSION_alex */
#ifndef MIN_TOOL_VERSION_alex
#define MIN_TOOL_VERSION_alex(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_alex */
/* tool gcc-11 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "11"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  11 || \
  (major1) == 11 && (major2) <  0 || \
  (major1) == 11 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-1.20.0 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "1.20.0"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.2.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.38 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.38"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  38 || \
  (major1) == 2 && (major2) == 38 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "LaboNotification-0.1.0.0-6gaSpAPKEyp1TrtVXHaTjg-LaboNotification-exe"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
